name: 🤖 Daily Qubit AI/ML Post

on:
  schedule:
    - cron: '30 13,20 * * *' 
  workflow_dispatch: 

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_AUTO_COMMIT }} 
          fetch-depth: 0 
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        
      # Step 1: Use the official action to install and start the Ollama service.
      # This action's only job is to get the server running in the background.
      - name: Setup and Start Ollama
        uses: ai-action/setup-ollama@v1

      # Step 2: Use the Ollama CLI to pull the required model.
      # This command communicates with the background server started in the previous step.
      - name: Pull Ollama Model
        run: ollama pull phi3:3.8b-mini-4k-instruct
        
      # Step 3: Verify that the model is now present.
      - name: Verify Model was Pulled
        run: |
          echo "Running 'ollama list' to verify model presence..."
          ollama list
          if ! ollama list | grep -q "phi3:3.8b-mini-4k-instruct"; then
            echo "::error::Verification failed! The model was not found after the pull command."
            exit 1
          fi
          echo "✅ Model verification successful."
        
      - name: Run Content Generation Script (Daily)
        run: python automation_script.py --type daily
        env:
          GH_TOKEN_AUTO_COMMIT: ${{ secrets.GH_TOKEN_AUTO_COMMIT }}