name: 🤖 Daily Qubit AI/ML Post

on:
  schedule:
    # Runs twice daily at 8:30 AM CDT (13:30 UTC) and 3:30 PM CDT (20:30 UTC)
    - cron: '30 13,20 * * *' 
  workflow_dispatch: 

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_AUTO_COMMIT }} 
          fetch-depth: 0 
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        
      # -----------------------------------------------------------------
      # --- FINAL, ROBUST FIX: Use the Official Setup Ollama Action ---
      # -----------------------------------------------------------------
      - name: Setup and Start Ollama
        uses: ai-action/setup-ollama@v1
        with:
          # This will download the specific version of Ollama and start it as a background service.
          # The action handles all networking and process management.
          ollama-version: '0.1.42' # Pinning to a known stable version
          
          # This will pull the model and make it available for your script.
          # The action will wait until the pull is complete.
          models: |
            phi3:3.8b-mini-4k-instruct

      - name: Verify Ollama is Running
        run: ollama list
        
      - name: Run Content Generation Script (Daily)
        run: python automation_script.py --type daily
        env:
          GH_TOKEN_AUTO_COMMIT: ${{ secrets.GH_TOKEN_AUTO_COMMIT }}