# daily_post.yml
name: 🤖 Daily Qubit AI/ML Post

on:
  schedule:
    - cron: '30 13,20 * * *' 
  workflow_dispatch: 

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_AUTO_COMMIT }} 
          fetch-depth: 0 
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        
      # Using the official action to set up the service AND pull the model
      - name: Setup and Start Ollama
        uses: ai-action/setup-ollama@v1
        with:
          models: |
            phi3:3.8b-mini-4k-instruct

      - name: Verify Model was Pulled
        run: |
          echo "Running 'ollama list' to verify model presence..."
          ollama list
          if ! ollama list | grep -q "phi3:3.8b-mini-4k-instruct"; then
            echo "::error::Verification failed! The required model was not pulled by the setup action."
            exit 1
          fi
          echo "Model verification successful."
        
      - name: Run Content Generation Script (Daily)
        run: python automation_script.py --type daily
        env:
          GH_TOKEN_AUTO_COMMIT: ${{ secrets.GH_TOKEN_AUTO_COMMIT }}