name: 🤖 Daily Qubit AI/ML Post

on:
  schedule:
    - cron: '30 13,20 * * *' 
  workflow_dispatch: 

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_AUTO_COMMIT }} 
          fetch-depth: 0 
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        
      # Step 1: Use the official action to install Ollama and start the background server.
      - name: Setup and Start Ollama
        uses: ai-action/setup-ollama@v1

      # Step 2: Explicitly wait for the background service to be fully ready.
      # This is the critical step that solves the race condition between workflow steps.
      - name: Wait for Ollama to be ready
        run: |
          echo "Waiting for Ollama server to be ready..."
          for i in {1..12}; do
            if ollama list > /dev/null 2>&1; then
              echo "✅ Ollama server is responsive."
              exit 0
            fi
            echo "Attempt $i: Ollama not ready yet. Waiting 5s..."
            sleep 5
          done
          echo "::error::Ollama server failed to start within the timeout."
          exit 1
        
      # Step 3: Now that the server is ready, pull the model.
      - name: Pull Ollama Model
        run: ollama pull phi3:3.8b-mini-4k-instruct
        
      # Step 4: Verify the model is present before running the Python script.
      - name: Verify Model was Pulled
        run: |
          echo "Verifying model presence..."
          if ! ollama list | grep -q "phi3:3.8b-mini-4k-instruct"; then
            echo "::error::Verification failed! Model not found after pull command."
            exit 1
          fi
          echo "✅ Model verification successful."
        
      - name: Run Content Generation Script (Daily)
        run: python automation_script.py --type daily
        env:
          GH_TOKEN_AUTO_COMMIT: ${{ secrets.GH_TOKEN_AUTO_COMMIT }}